run:
  timeout: 5m
  # Do NOT run linters on test files
  tests: false

linters:
  enable:
    - govet
    - staticcheck
    - gofmt

linters-settings:
  gofmt:
    simplify: true

issues:
  # Exclude test files and testdb.go from linters
  exclude-rules:
    - path: '.*_test\.go$'
      linters:
        - "*"
  exclude-dirs:
    - internal/testutil
    
