run:
  timeout: 5m
  # Do NOT run linters on test files
  tests: false

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    # - unparam
    - unused

linters-settings:
  gofmt:
    simplify: true
  unparam:
    check-exported: true

