// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ratelimit.proto

package ratelimit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitRequest) Reset() {
	*x = RateLimitRequest{}
	mi := &file_ratelimit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitRequest) ProtoMessage() {}

func (x *RateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ratelimit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitRequest.ProtoReflect.Descriptor instead.
func (*RateLimitRequest) Descriptor() ([]byte, []int) {
	return file_ratelimit_proto_rawDescGZIP(), []int{0}
}

func (x *RateLimitRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type RateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Remaining     int32                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	RetryAfterMs  int64                  `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitResponse) Reset() {
	*x = RateLimitResponse{}
	mi := &file_ratelimit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitResponse) ProtoMessage() {}

func (x *RateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ratelimit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitResponse.ProtoReflect.Descriptor instead.
func (*RateLimitResponse) Descriptor() ([]byte, []int) {
	return file_ratelimit_proto_rawDescGZIP(), []int{1}
}

func (x *RateLimitResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *RateLimitResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *RateLimitResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

var File_ratelimit_proto protoreflect.FileDescriptor

const file_ratelimit_proto_rawDesc = "" +
	"\n" +
	"\x0fratelimit.proto\x12\tratelimit\"\"\n" +
	"\x10RateLimitRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"q\n" +
	"\x11RateLimitResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x05R\tremaining\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\x03R\fretryAfterMs2_\n" +
	"\x10RateLimitService\x12K\n" +
	"\x0eCheckRateLimit\x12\x1b.ratelimit.RateLimitRequest\x1a\x1c.ratelimit.RateLimitResponseB=Z;github.com/zhejian/url-shortener/gateway/internal/ratelimitb\x06proto3"

var (
	file_ratelimit_proto_rawDescOnce sync.Once
	file_ratelimit_proto_rawDescData []byte
)

func file_ratelimit_proto_rawDescGZIP() []byte {
	file_ratelimit_proto_rawDescOnce.Do(func() {
		file_ratelimit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ratelimit_proto_rawDesc), len(file_ratelimit_proto_rawDesc)))
	})
	return file_ratelimit_proto_rawDescData
}

var file_ratelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ratelimit_proto_goTypes = []any{
	(*RateLimitRequest)(nil),  // 0: ratelimit.RateLimitRequest
	(*RateLimitResponse)(nil), // 1: ratelimit.RateLimitResponse
}
var file_ratelimit_proto_depIdxs = []int32{
	0, // 0: ratelimit.RateLimitService.CheckRateLimit:input_type -> ratelimit.RateLimitRequest
	1, // 1: ratelimit.RateLimitService.CheckRateLimit:output_type -> ratelimit.RateLimitResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ratelimit_proto_init() }
func file_ratelimit_proto_init() {
	if File_ratelimit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ratelimit_proto_rawDesc), len(file_ratelimit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ratelimit_proto_goTypes,
		DependencyIndexes: file_ratelimit_proto_depIdxs,
		MessageInfos:      file_ratelimit_proto_msgTypes,
	}.Build()
	File_ratelimit_proto = out.File
	file_ratelimit_proto_goTypes = nil
	file_ratelimit_proto_depIdxs = nil
}
